name: Memoize Actions

on:
  push:
    branches: [ "main" ]

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: install Dependencies
      run: npm install
    - name: Execute test
      run: npm run test 
    - name: compilation Typescript
      uses: icrawl/action-tsc@v1
      if: success() 
    - name: Exit on Test Failure
      run: exit 1
      if: failure()

